### ISSUE TITLE
[BUG] Workout Entries Disappear & Do Not Award Coins

### ISSUE THREAD

**Issue by winstonbullen** [m-arquiza/Workoutholic#84]
Steps to Reproduce:
1. Run the app via Android Studio
2. Click on the `Entries` tab
3. Create a new entry
4. Click on the `Buddy` tab
5. Click back to the `Entries` tab

Expected Behavior:
The workout is still there, and coins have been awarded for the workout.

Actual Behavior:
The workout is gone, and coins were not awarded.

Type of Bug:
Missing functionality integral to the idea of the system. 
Not mentioned as missing functionality in the user documentation.

**Comment by ashleyperis** [comment]
Hi Winston! We looked into this and found out we forgot to mention that it was a missing functionality in the user documentation, sorry for the confusion. Thank you for pointing this out and for the detailed post about this issue. The issue has been resolved, if you wanted to follow up on this/check if it functions properly now.
